Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/09/2023
Var
   // Seção de Declarações das variáveis
   c: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para c <-1 ate 100 faca
      se c % 10 = 0 entao
         escreval(c," é um múltiplo de 10")
      senao
         escreval(c)
      fimse
   fimpara


Fimalgoritmo