Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/09/2023
Var
   // Seção de Declarações das variáveis
   contador: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   // REPETIÇÃO WHILE

   contador <- 1
   enquanto   contador <= 10 faca
      escreval("Já se passaram", contador, " vezes")

      contador <- contador + 1

   fimEnquanto

Fimalgoritmo