Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/09/2023
Var
   // Seção de Declarações das variáveis
   c: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para c<-100 ate 200 faca
      se c%2 <> 0 entao
         escreval(c)
      fimse
   fimPara

Fimalgoritmo