Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/09/2023
Var
// Seção de Declarações das variáveis 
valor, a, b : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Insira o valor")
leia(valor)
se valor > 0 entao
a <- valor
escreval(valor," é positivo e foi salvo em A")
senao
b <- valor
escreval(valor," é negativo e foi salvo em B")
fimse

Fimalgoritmo